@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "*",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.craft.demo.scheduler.ScoreLoaderCron",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_94921248 { 
   	label=craft
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1214830351 { 
   	label=demo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CSVfileReader282476231[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CSVfileReader</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ readFile(fileLocation: String): List&lt;PlayerData&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FileOperationsImpl1989567041[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FileOperationsImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getFile(fileLocation: String): File</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FileReaderFactory282476231[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FileReaderFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getFileReader(fileType: String): FileReader</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FileUtilities1989567041[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FileUtilities</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   fileLocation: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fileOperations: FileOperationsImpl [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   scoreRepository: ScoreRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ readCSVFile(): CSVParser</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ScoreLoaderCron1412942411[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ScoreLoaderCron</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   fileLocation: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fileReaderFactory: FileReaderFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fileUtilities: FileUtilities [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   lastUpdatedTimestamp: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   repository: ScoreRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   timeCheckpointRepository: TimeCheckpointRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ loadScoresToDb()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
FileUtilities1989567041 -> FileOperationsImpl1989567041[label="fileOperations
[0..1]"];
ScoreLoaderCron1412942411 -> CSVfileReader282476231[arrowhead=none];
ScoreLoaderCron1412942411 -> FileReaderFactory282476231[label="fileReaderFactory
[0..1]"];
ScoreLoaderCron1412942411 -> FileUtilities1989567041[label="fileUtilities
[0..1]"];
    
}
@enduml