@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.craft.demo.scheduler.ScoreLoaderCron#loadScoresToDb()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "*",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.craft.demo.scheduler.ScoreLoaderCron",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_94921248 { 
   	label=craft
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1214830351 { 
   	label=demo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_19710172 { 
   	label=FileReaderFactory
	labeljust=l
	fillcolor=white
	style=filled
   
   FileReaderFactory282476231XXXgetFileReader1808118735[
	label="+ getFileReader()"
	style=filled
	fillcolor=white
	tooltip="FileReaderFactory

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_756608080 { 
   	label=ScoreLoaderCron
	labeljust=l
	fillcolor=white
	style=filled
   
   ScoreLoaderCron1412942411XXXloadScoresToDb0[
	label="+ loadScoresToDb()"
	style=filled
	fillcolor=white
	tooltip="ScoreLoaderCron

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_838460194 { 
   	label=CSVfileReader
	labeljust=l
	fillcolor=white
	style=filled
   
   CSVfileReader282476231XXXreadFile1808118735[
	label="+ readFile()"
	style=filled
	fillcolor=white
	tooltip="CSVfileReader

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ScoreLoaderCron1412942411XXXloadScoresToDb0 -> CSVfileReader282476231XXXreadFile1808118735;
ScoreLoaderCron1412942411XXXloadScoresToDb0 -> FileReaderFactory282476231XXXgetFileReader1808118735;
    
}
@enduml